In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression

# Feature 1: Residenital Units Completed Each Month

In [2]:
res_con = pd.read_csv('res_construction.csv')

In [3]:
res_con = res_con[['REF_DATE', 'Type of structure', 'VALUE']]

In [4]:
res_con = res_con.rename(columns={'REF_DATE': 'Period','Type of structure': 'Type', 'VALUE':'Count'})

In [5]:
res_con = res_con[res_con['Type'] == 'Total residential']

In [6]:
res_con = res_con.drop('Type', axis=1).set_index('Period', drop=True)

In [7]:
res_con.shape, res_con.dtypes 

((16, 1),
 Count    int64
 dtype: object)

In [8]:
res_con = np.array(res_con)

In [9]:
res_con

array([[1251],
       [ 805],
       [ 970],
       [1500],
       [1683],
       [2045],
       [1562],
       [1439],
       [1373],
       [1366],
       [1835],
       [1429],
       [1536],
       [1262],
       [1265],
       [1416]])

## Feature 1 Complete: Residential Units Completed Each Month

# Feature 2: Completed Units Absorbtion Each Month

In [10]:
df = pd.read_csv('absorb_units.csv')
df = df[['Time','All']].set_index('Time', drop=True)
df = df.rename(columns={'All':'Count'})

In [11]:
df = df.loc[df.index.str.contains('2023|2022')]

In [12]:
df = df['Count'].astype('int64')

In [13]:
df = df.values.reshape(-1,1)

In [14]:
df.shape, df.dtype

((17, 1), dtype('int64'))

In [15]:
df

array([[577],
       [471],
       [548],
       [645],
       [605],
       [656],
       [563],
       [620],
       [588],
       [548],
       [630],
       [705],
       [481],
       [615],
       [657],
       [695],
       [948]])

## Feature 2 Complete: Abosrbed Residential Units Each Month

# Feature 3: Absorbed Unit Costs

In [16]:
df = pd.read_csv('absorb_price.csv')
df = df[['Time','Average']].set_index('Time', drop=True)
df

Average
Time                  
1990 January   157,461
1990 February  145,924
1990 March     153,323
1990 April     158,684
1990 May       169,382
...                ...
2023 February  719,495
2023 March     721,938
2023 April     743,584
2023 May       766,959
Source             NaN

[402 rows x 1 columns]

In [17]:
df = df.loc[df.index.str.contains('2022|2023')]

In [18]:
df = df.Average.str.replace(',','').astype('int64')

In [19]:
df = df.values.reshape(-1,1)
df.shape

(17, 1)

In [20]:
df

array([[620090],
       [630697],
       [652992],
       [651990],
       [689070],
       [683979],
       [657916],
       [720625],
       [707905],
       [690682],
       [700049],
       [737179],
       [699978],
       [719495],
       [721938],
       [743584],
       [766959]])

## Feature 3 Complete: AVG. Absorbiton Price of Single Family/Attached Homes

In [21]:
# Feature 4: 